name: macos应用程序构建
run-name: macos应用程序构建
on: [release, workflow_dispatch]
jobs:
  make-macos-package:
    runs-on: macos-latest
    steps:
      - name: 安装 tree 命令
        run: brew install tree
      - name: 克隆仓库代码
        uses: actions/checkout@v4
      - name: 安装项目依赖库
        run: npm install
      - name: 应用程序打包
        run: npm run make
      - name: 显示构件目录结构
        run: tree ./out/make
