name: electron应用程序构建
on: [push, workflow_dispatch]
jobs:
  make-ubuntu-package:
    runs-on: ubuntu-latest
    steps:
      - name: 克隆仓库代码
        uses: actions/checkout@v4
      - name: 安装项目依赖库
        run: npm install
      - name: 应用程序打包
        run: npm run make
      - name: 显示构件目录结构
        run: ls -R ${{ github.workspace }}/out/make
